version: '3.4'

services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    volumes:
      - ./app:/usr/share/nginx/html/app
    environment:
      API_URL: /app/index.yaml
    restart: always